"""empty message

Revision ID: 68d5efebdf5a
Revises: None
Create Date: 2016-04-18 02:00:02.500700

"""

# revision identifiers, used by Alembic.
revision = '68d5efebdf5a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('email', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('name', sa.String(), nullable=False))
    op.drop_constraint(u'posts_author_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'author_id')
    op.drop_column('posts', 'description')
    op.drop_column('posts', 'title')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'posts_author_id_fkey', 'posts', 'users', ['author_id'], ['id'])
    op.drop_column('posts', 'name')
    op.drop_column('posts', 'email')
    ### end Alembic commands ###
